name: revalesuva
description: "בית לבריאות וריפוי טבעי"

version: 1.0.0+7

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get: ^4.7.2
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.5.3
  flutter_displaymode: ^0.6.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  pinput: ^5.0.1
  file_picker: ^10.0.0
  dropdown_button2: ^2.3.9
  persistent_bottom_nav_bar_v2: ^5.3.1
  chewie: ^1.11.1
  json_annotation: ^4.9.0
  flutter_widget_from_html: ^0.16.0
  shimmer: ^3.0.0
  flutter_media_downloader: ^2.0.0
  fl_chart: ^0.70.2
  table_calendar: ^3.1.3
  percent_indicator: ^4.2.4
  hive_flutter: ^1.1.0
  expansion_tile_group: ^2.2.0
  audio_session: ^0.1.24
  just_audio: ^0.9.46
  audio_service: ^0.18.17
  syncfusion_flutter_sliders: ^29.1.35
  syncfusion_flutter_core: ^29.1.35
  image: ^4.5.4
  flutter_staggered_grid_view: ^0.7.0
  screenshot: ^3.0.0
  widgets_to_image: ^1.0.0
  flutter_local_notifications: ^19.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5
  share_plus: ^10.1.4
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.5
  photo_view: ^0.15.0
  vimeo_video_player: ^1.0.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
