import 'package:get/get.dart';

//finnish, sweden, English
class Localization extends Translations {
  static Map<String, Map<String, String>> translations = {
    'en_US': {
      'Copyright': 'Copyright by ©Revalesuva',
      'Username': 'Username',
      'Password': 'Password',
      'New Password': 'New Password',
      'Current Password': 'Current Password',
      'Confirm Password': 'Confirm Password',
      'Login': 'Login',
      'I forgot the password': 'I forgot the password',
      'Hi': 'Hi',
      'Before we start, we would love to get to know you better...':
          'Before we start, we would love to get to know you better...',
      'Name': 'Name',
      'Full name': 'Full name',
      'Phone number': 'Phone number',
      'Email': 'Email',
      'Enter email': 'Enter email',
      "Next step": 'Next step',
      "Email is required": 'Email is required',
      "Email is Invalid": 'Email is Invalid',
      "Password is required": 'Password is required',
      "Otp is required": 'Otp is required',
      "Otp is Invalid": 'Otp is Invalid',
      "Pincode is required": 'Pincode is required',
      "Name is required": 'Name is required',
      "Phone Number is required": 'Phone Number is required',
      "Gender is required": 'Gender is required',
      'Username is empty': 'Username is empty',
      "Some details to remember where we started": "Some details to remember where we started",
      "Details that are not mandatory fields can be entered later":
          "Details that are not mandatory fields can be entered later",
      "Initial weight": 'Initial weight',
      "Weight": 'Weight',
      "Height": 'Height',
      "Upload blood tests": 'Upload blood tests',
      "Age": 'Age',
      "Gender": 'Gender',
      "Regular menstruation": 'Regular menstruation',
      "Last menstruation date": 'Regular menstruation',
      "Number of cycle days": 'Number of cycle days',
      "Measurements": 'Measurements',
      "How to measure?": 'How to measure?',
      "Date of last period": "Date of last period",
      "Chest circumference": 'Chest circumference',
      "Abdominal circumference": 'Abdominal circumference',
      "Hip circumference": 'Hip circumference',
      "Circumference": 'Circumference',
      "Before photos": 'Before photos',
      "How to take photos?": 'How to take photos?',
      "Front": 'Front',
      "Side": 'Side',
      "Back": 'Back',
      "Previous step": 'Previous step',
      "kg": 'kg',
      "cm": 'cm',
      "A little more and we're done": 'A little more and we\'re done',
      "Street": 'Street',
      "Postal code": 'Postal code',
      "Apartment": 'Apartment',
      "House": 'House',
      "City": 'City',
      "Personal status": 'Personal status',
      "Occupation": 'Occupation',
      "Are there any medical problems/diseases you suffer from":
          'Are there any medical problems/diseases you suffer from',
      "No": 'No',
      "Yes": 'Yes',
      "Have you ever been hospitalized in the past? (excluding childbirth)":
          "Have you ever been hospitalized in the past? (excluding childbirth)",
      "Description": "Description",
      "Next question": "Next question",
      "We finished!": "We finished!",
      "Previous question": "Previous question",
      "Female": 'Female',
      'Male': 'Male',
      'Regular Period': 'Regular Period',
      'Irregular Period': 'Irregular Period',
      'Breastfeeding Period': 'Breastfeeding Period',
      'Pregnant Period': 'Pregnant Period',
      'Not accepting anymore': 'Not accepting anymore',
      'is required': 'is required',
      'So what is actually a quarter to seven': 'So what is actually a quarter to seven',
      "Let's get started": "Let's get started",
      "Camera": 'Camera',
      'Gallery': 'Gallery',
      'Store': 'store',
      'My stars': 'My stars',
      'Hizukit Mehadas': 'Hizukit Mehadas',
      'Products & recipes': 'Products & recipes',
      'My plan': 'My plan',
      'Home page': 'Home page',
      'Personal area': 'Personal area',
      'Nutrition plans': 'Nutrition plans',
      'Ice Therapy': 'Ice Therapy',
      'Articles': 'Articles',
      'Podcasts': 'Podcasts',
      'Workshops and events': 'Workshops and events',
      'Healthy consumption': 'Healthy consumption',
      'Contact': 'Contact',
      'Terms and Conditions': 'Terms and Conditions',
      "General messages": "General messages",
      "My orders": "My orders",
      "The products I loved": "The products I loved",
      "My workshops/events": "My workshops/events",
      "My shopping cart": "My shopping cart",
      "My shopping list": 'My shopping list',
      "The recipes I loved": "The recipes I loved",
      "Tools": "Tools",
      "Weight and measurements tracking": "Weight and measurements tracking",
      "My plans": "My plans",
      "Personal profile": "Personal profile",
      "General": "General",
      "Image editing": "Image editing",
      "My Favorite Recipes": 'My Favorite Recipes',
      "Accessibility": "Accessibility",
      "Terms of use policy": "Terms of use policy",
      "Privacy policy": "Privacy policy",
      "Shipping and returns policy": "Shipping and returns policy",
      "Regulations": "Regulations",
      "General information and contact details": "General information and contact details",
      "Body data and medical information": "Body data and medical information",
      "Back to": "Back to",
      "Edit": "Edit",
      "Login details": "Login details",
      "Save changes": "Save changes",
      "New password": "New password",
      "Your request to change the password has been received. Please confirm the change in the email updated in the system within 48 hours":
          "Your request to change the password has been received. Please confirm the change in the email updated in the system within 48 hours.",
      "Date of Birth": "Date of Birth",
      "Body data": "Body data",
      "Medical questionnaire": "Medical questionnaire",
      "Viewing blood test form": "Viewing blood test form",
      "Enter ovulation_calculator calculator": "Enter ovulation_calculator calculator",
      "Contact Us": "Contact Us",
      "Coach Chat": "Coach Chat",
      "Technical Support": "Technical Support",
      "Inquiry Regarding Service": "Inquiry Regarding Service",
      "Send": "Send",
      "I need help with": "I need help with",
      "Details": "Details",
      "Thank you for your inquiry!": "Thank you for your inquiry!",
      "Your inquiry will be handled within 24 hours": "Your inquiry will be handled within 24 hours",
      "Return to homepage": "Return to homepage",
      "Married": "Married",
      "Unmarried": "Unmarried",
      "Jerusalem": "Jerusalem",
      "Tel Aviv-Yafo": "Tel Aviv-Yafo",
      "Haifa": "Haifa",
      "Rishon LeZion": "Rishon LeZion",
      "Ashdod": "Ashdod",
      "Beersheba": "Beersheba",
      "Petah Tikva": "Petah Tikva",
      "Netanya": "Netanya",
      "Holon": "Holon",
      "Bnei Brak": "Bnei Brak",
      "Bat Yam": "Bat Yam",
      "Ramat Gan": "Ramat Gan",
      "Ashkelon": "Ashkelon",
      "Rehovot": "Rehovot",
      "Beit Shemesh": "Beit Shemesh",
      "Kfar Saba": "Kfar Saba",
      "Herzliya": "Herzliya",
      "Hadera": "Hadera",
      "Modi'in-Maccabim-Re'ut": "Modi'in-Maccabim-Re'ut",
      "Eilat": "Eilat",
      "Logout": "Logout",
      "Are you sure you want to log out": "Are you sure you want to log out?",
      "OTP is being sent to your email. Please check your email and fill it in":
          "OTP is being sent to your email. Please check your email and fill it in",
      "Good morning": "Good morning",
      "Good afternoon": "Good afternoon",
      "Good evening": "Good evening",
      "What's on the agenda for today?": "What's on the agenda for today?",
      "Delete": "Delete",
      "Select All": "Select All",
      "Ovulation Calculator": "Ovulation Calculator",
      "Daily Nutrition Planning": "Daily Nutrition Planning",
      "Daily Reports": "Daily Reports",
      "Daily Report": "Daily Report",
      "Daily Report - Day {}": "Daily Report - Day {}",
      "Weekly Reports": "Weekly Reports",
      "Weekly Report": "Weekly Report",
      "Weekly Report - No. {}": "Weekly Report - No. {}",
      "Intuitive Writing for Myself": "Intuitive Writing for Myself",
      "My Successes": "My Successes",
      "Fasting Calculator": "Fasting Calculator",
      "Nutritional Information": "Nutritional Information",
      "Mark as Unread": "Mark as Unread",
      "Mark as Read": "Mark as Read",
      "You have not entered the current weight yet!": "You have not entered the current weight yet!",
      "Click here to weigh yourself": "Click here to weigh yourself",
      "We will meet on {} for the next weigh-in": "We will meet on {} for the next weigh-in",
      "Previous Weigh-in Date: {}": "Previous Weigh-in Date: {}",
      "Last": "Last",
      "The system detects that you are ovulating, so it is not recommended to weigh yourself these days":
          "The system detects that you are ovulating, so it is not recommended to weigh yourself these days",
      "The next weigh-in will take place on": "The next weigh-in will take place on",
      "Please wait until the end of hormonal days!": "Please wait until the end of hormonal days!",
      "It's time to measure your circumference": "It's time to measure your circumference",
      "It's time for your weekly weigh-in!": "It's time for your weekly weigh-in!",
      "Last Hip Line": "Last Hip Line",
      "Last Abdominal Line": "Last Abdominal Line",
      "Last Chest Line": "Last Chest Line",
      "Champion!": "Champion!",
      "Very nice progress": "Very nice progress",
      "Keep it up": "Keep it up",
      "Weight Entry": "Weight Entry",
      "Confirmation": "Confirmation",
      "Edit weight": "Edit weight",
      "View Data History": "View Data History",
      "You are on the right track!": "You are on the right track!",
      "We will meet on {} for the next measurement": "We will meet on {} for the next measurement",
      "Weighing and Circumference Data History": "Weighing and Circumference Data History",
      "Abdominal Line": "Abdominal Line",
      "Chest Line": "Chest Line",
      "Hip Line": "Hip Line",
      "First Weigh-in": "First Weigh-in",
      "Last Weigh-in": "Last Weigh-in",
      "So far you have lost {} kg, which is x percent of your body weight":
          "So far you have lost {} kg, which is x percent of your body weight",
      "Date": "Date",
      "First Measurement": "First Measurement",
      "Last Measurement": "Last Measurement",
      "January": "January",
      "February": "February",
      "March": "March",
      "April": "April",
      "May": "May",
      "June": "June",
      "July": "July",
      "August": "August",
      "September": "September",
      "October": "October",
      "November": "November",
      "December": "December",
      "Hormonal Days": "Hormonal Days",
      "Ovulation": "Ovulation",
      "Menstruation": "Menstruation",
      "Edit Data": "Edit Data",
      "Menstruation Status:": "Menstruation Status:",
      "Regular": "Regular",
      "Save Data": "Save Data",
      "Submit": "Submit",
      "Intuitive Writing": "Intuitive Writing",
      "New Note": "New Note",
      "Save": "Save",
      "list": "list",
      "To Read": "To Read",
      "No Data found": "No Data found",
      "Breakfast": "Breakfast",
      "Mark if Done": "Mark if Done",
      "Vegetables": "Vegetables",
      "Proteins": "Proteins",
      "Carbohydrates": "Carbohydrates",
      "Fats": "Fats",
      "Lunch": "Lunch",
      "Dinner": "Dinner",
      "Send Plan to Coach": "Send Plan to Coach",
      "Confirm": "Confirm",
      "Cannot Select": "Cannot Select",
      "Daily Plan Sent to Coach": "Daily Plan Sent to Coach",
      "Update What You Did at the End of the Day": "Update What You Did at the End of the Day",
      "The daily plan is sent to the coach. At the end of the day, update what you have done":
          "The daily plan is sent to the coach. At the end of the day, update what you have done",
      "Search by free text": "Search by free text",
      "Day": "Day",
      "Fasting": "Fasting",
      "Report approval": "Report approval",
      "Not at all": "Not at all",
      "Very": "מאוד",
      "More than": "More than",
      "Number of Target Hours": "Number of Target Hours",
      "I started fasting earlier": "I started fasting earlier",
      "Start Fasting": "Start Fasting",
      "Start Fasting Timer": "Start Fasting Timer",
      "Hours of Fasting {}": "Hours of Fasting {}",
      "The target is ": "The target is ",
      " hours! Ready": " hours! Ready",
      "To end the fast": "To end the fast",
      "Press to Stop": "Press to Stop",
      "Edit Fasting Timer": "Edit Fasting Timer",
      "Number of Intended Fasting Hours": "Number of Intended Fasting Hours",
      "Start Time": "Start Time",
      "Eating window": "Eating window",
      "hours": "hours",
      "For fasting editing": "For fasting editing",
      "Duration": "Duration",
      "Add New Fast": "Add New Fast",
      "Minutes": "Minutes",
      "Hour": "Hour",
      "Cancel": "Cancel",
      "Update": "Update",
      "Fast Clock Update": "Fast Clock Update",
      "Fast Editing": "Fast Editing",
      "Update Fasting Start Time": "Update Fasting Start Time",
      "Fasting History": "Fasting History",
      "Products and Recipes": "Products and Recipes",
      "Recommended Products": "Recommended Products",
      "Recipes": "Recipes",
      "Recommended": "Recommended",
      "Add": "Add",
      "To Shopping List": "To Shopping List",
      "Share": "Share",
      "All Products": "All Products",
      "All Recipes": "All Recipes",
      "Filter by": "Filter by",
      "Vegan": "Vegan",
      "Vegetarian": "Vegetarian",
      "Meat": "Meat",
      "Dairy": "Dairy",
      "To add to the shopping list, click on the square":
          "To add to the shopping list, click on the square",
      "Ingredients": "Ingredients",
      "Add to shopping list": "Add to shopping list",
      "Add to Cart": "Add to Cart",
      "Are you sure you want to remove item from cart": "Are you sure you want to remove item from cart",
      "Checkout": "Checkout",
      "Total to be paid": "Total to be paid",
      "Sub Total": "Sub Total",
      "You may also be interested": "You may also be interested",
      "Hadas's Strengthening": "Hadas's Strengthening",
      "Weekly Torah Portion": "Weekly Torah Portion",
      "Strength Training": "Strength Training",
      "Flexibility": "Flexibility",
      "Learning to Cook": "Learning to Cook",
      "To Watch": "To Watch",
      "Order details": "Order details",
      "Total Amount": "Total Amount",
      "Items": "Items",
      "Cancel Order": "Cancel Order",
      "Are you sure you want to cancel this order?": "Are you sure you want to cancel this order?",
      "Pending": "Pending",
      "Processing": "Processing",
      "Shipped": "Shipped",
      "Delivered": "Delivered",
      "Canceled": "Canceled",
      "Returned": "Returned",
      "Refunded": "Refunded",
      "Learn more": "Learn more",
      "For More Details": "For More Details",
      "On Date": "On Date",
      "Free of Charge": "Free of Charge",
      "NIS": "NIS",
      "Participants": "Participants",
      "So, what's in the event?": "So, what's in the event?",
      "Registration for {}": "Registration for {}",
      "Registration": "Registration",
      "On the date": "On the dat",
      "From": "From",
      "Past events": "Past events",
      "Are you sure you want to delete this all product?":
          "Are you sure you want to delete this all product?",
      "Your order is on its way!": "Your order is on its way!",
      "Thank you for your purchase": "Thank you for your purchase",
      "Invoice is waiting for you": "Invoice is waiting for you",
      "in the email: {}": "in the email: {}",
      "The delivery will arrive at your home in about 5 business days":
          "The delivery will arrive at your home in about 5 business days",
      "For questions and more details, you can contact us at: {}":
          "For questions and more details, you can contact us at: {}",
      "Back to Home Page": "Back to Home Page",
      "Cycle Length (number of days between periods, usually between 26-50 days)":
          "Cycle Length (number of days between periods, usually between 26-50 days)",
      "Weight not entered yet": "Weight not entered yet",
      "Click here to weigh in": "Click here to weigh in",
      "Select all": "Select all",
      "My Programs": "My Programs",
      "Continuation Programs": "Continuation Programs",
      "Completed Programs": "Completed Programs",
      "Program Summary": "Program Summary",
      "So what's on the agenda?": "So what's on the agenda?",
      "Lessons": "Lessons",
      "Tasks": "Tasks",
      "My principles puzzle": "My principles puzzle",
      "Content library": "Content library",
      "Completed {1}": "Completed {1}",
      "A new informational video has been uploaded": "A new informational video has been uploaded",
      "Lesson Summary": "Lesson Summary",
      "Lesson": "Lesson",
      "Remaining to Watch: {} min": "Remaining to Watch: {} min",
      "To watch the video, you must complete viewing the previous video":
          "To watch the video, you must complete viewing the previous video.",
      "At the end of the lesson, you will be able to view the lesson summary and tasks":
          "At the end of the lesson, you will be able to view the lesson summary and tasks.",
      "Download File": "Download File",
      "My Tasks from the Lesson": "My Tasks from the Lesson",
      "All Tasks": "All Tasks",
      "My Tasks": "My Tasks",
      "To the principles puzzle": "To the principles puzzle",
      "Show all incomplete tasks": "Show all incomplete tasks",
      "Show all": "Show all",
      "In summary": "In summary",
      "Instructor: {}": "Instructor: {}",
      "The hour is full, {} on the waiting list": "The hour is full, {} on the waiting list",
      "Exit from Waiting List": "Exit from Waiting List",
      "To Waiting List": "To Waiting List",
      "Cancel Registration": "Cancel Registration",
      "Register": "Register",
      "{} participants": "{} participants",
      "Well done! You have completed the program and now it's time to summarize. The summary is for you and for us":
          "Well done! You have completed the program and now it's time to summarize. The summary is for you and for us.",
      "Click here to fill out": "Click here to fill out",
      "Program Completion Report": "Program Completion Report",
      "Finish": "Finish",
      "Move your heart on the scale according to your feelings":
          "Move your heart on the scale according to your feelings",
      "Before and After Photos": "Before and After Photos",
      "Amazing! See your progress": "Amazing! See your progress",
      "Thank you for participating in the program": "Thank you for participating in the program",
      "We look forward to seeing you in the upcoming programs":
          "We look forward to seeing you in the upcoming programs",
      "The Stars Program": "The Stars Program",
      "Undecided? Fill out this form for advice": "Undecided? Fill out this form for advice",
      "I need advice regarding the program": "I need advice regarding the program",
      "Please select plan": "Please select plan",
      "Weight and Measurement History": "Weight and Measurement History",
      "Weight and Measurement Data History": "Weight and Measurement Data History",
      "Summary of My Personal Journey": "Summary of My Personal Journey",
      "My Victory Picture": "My Victory Picture",
      "Before and After Pictures": "Before and After Pictures",
      "Share Photo": "Share Photo",
      "Next page": "Next page",
      "Previous page": "Previous page",
      "The Vegetable Challenge": "The Vegetable Challenge",
      "Day Number": "Day Number",
      "Vegetable Summary until Day No. {}": "Vegetable Summary until Day No. {}",
      "Red/Orange/Purple Vegetables": "Red/Orange/Purple Vegetables",
      "Yellow/White Vegetables": "Yellow/White Vegetables",
      "Green Vegetables": "Green Vegetables",
      "Total Vegetables": "Total Vegetables",
      "Which vegetables do you plan to have today?": "Which vegetables do you plan to have today?",
      "At 20:00 you can confirm the final daily list and add to the challenge summary":
          "At 20:00 you can confirm the final daily list and add to the challenge summary",
      "Already Selected Before": "Already Selected Before",
      "Great! Add to the Weekly Summary": "Great! Add to the Weekly Summary",
      "So far you have earned {} stars!": "So far you have earned {} stars!",
      "Good morning, {}": "Good morning, {}",
      "Good afternoon, {}": "Good afternoon, {}",
      "Good evening, {}": "Good evening, {}",
      "Good night, {}": "Good night, {}",
      "Hello, {}": "Hello, {}",
      "So what's on the agenda today?": "So what's on the agenda today?",
      "Ovulation forecast": "Ovulation forecast",
      "Expected period": "Expected period",
      "For period editing": "For period editing",
      "For fast editing": "For fast editing",
      "days": "days",
      "Cycle day": "Cycle day",
      "Weighing": "Weighing",
      "Click here and weigh me": "Click here and weigh me",
      "Nutrition": "Nutrition",
      "Weekly portion": "Weekly portion",
      "For me": "For me",
      "The daily report must be filled out": "The daily report must be filled out",
      "The weekly report must be filled out": "The weekly report must be filled out",
      "completed the program home":
          "Great job! You have completed the program and now it is time to summarize. The summary is for you and for us",
      "Click here to fill it out": "Click here to fill it out",
      "Ice workshop": "Ice workshop",
      "Welcome to {1}, our next meeting will be at {2}, see you there!":
          "Welcome to {1}, our next meeting will be at {2}, see you there!",
      "Please complete all the answers": "Please complete all the answers",
      "Reminder to Fill Reports": "Reminder to Fill Reports",
      "Daily planning needs to be filled out": "Daily planning needs to be filled out",
      "A report is available for completion": "A report is available for completion",
      "Hey Sorry! Classes are closed today": "Hey Sorry! Classes are closed today",
      "Join the class on the link": "Join the class on the link",
      "Ovulation expected": "Ovulation expected",
      "Menstruation expected": "Menstruation expected",
      "customer": "customer",
      "Customer Options": "Customer Options",
      "Chat": "Chat",
      "blood report information": "blood report information",
      "Nutrition planning": "Nutrition planning",
      "snacks": "snacks",
      "Shopping list is empty":"Shopping list is empty",
      "Vegetable challenge will start after {} days":"Vegetable challenge will start after {} days",
      "No coach found":"No coach found",
    },
    'he_IL': {
      'Copyright': 'זכויות יוצרים מאת ©Revalesuva',
      'Username': 'שם משתמש',
      'Password': 'סיסמא',
      'New Password': 'סיסמה חדשה',
      'Current Password': 'סיסמה נוכחית',
      'Confirm Password': 'אשר סיסמה',
      'Login': 'כניסה',
      'I forgot the password': 'שכחתי את הסיסמא',
      'Hi': 'היי',
      'Before we start, we would love to get to know you better...':
          'לפני שמתחילות נשמח להכיר אותך יותר לעומק...',
      'Name': 'שם',
      'Full name': 'שם מלא',
      'Phone number': 'מספר טלפו',
      'Email': 'דוא"ל',
      'Enter email': 'הזן דוא"ל',
      "Next step": 'שלב הבא',
      "Email is required": 'דוא"ל נדרש',
      "Email is Invalid": 'דוא"ל לא חוקי',
      "Password is required": 'נדרשת סיסמא',
      "Otp is required": 'נדרש קוד אימות',
      "Otp is Invalid": 'קוד אימות לא חוקי',
      "Pincode is required": 'נדרש קוד מיקוד',
      "Name is required": 'נדרש שם',
      "Phone Number is required": 'נדרש מספר טלפון',
      "Gender is required": 'נדרש מין',
      'Username is empty': 'שם משתמש ריק',
      "Some details to remember where we started": 'קצת פרטים שנזכור מאיפה התחלנו',
      "Details that are not mandatory fields can be entered later":
          'פרטים שאינם שדה חובה ניתן להזין מאוחר יותר',
      "Initial weight": 'משקל ראשוני',
      "Weight": 'משקל',
      "Height": 'גובה',
      "Upload blood tests": 'העלאת בדיקות דם',
      "Age": 'גיל',
      "Gender": 'מין',
      "Regular menstruation": 'וסת סדירה',
      "Last menstruation date": 'תאריך וסת אחרון',
      "Number of cycle days": 'מספר ימי מחזור',
      "Measurements": 'היקפים',
      "How to measure?": 'איך   ?',
      "Date of last period": "תאריך וסת אחרון",
      "Chest circumference": 'היקף חזה',
      "Abdominal circumference": 'היקף בטן',
      "Hip circumference": 'היקף ירכיים',
      "Circumference": 'היקף',
      "Before photos": 'תמונות לפני',
      "How to take photos?": 'איך מצלמים?',
      "Front": 'חזית',
      "Side": 'צד',
      "Back": 'אחורה',
      "Previous step": 'שלב קודם',
      "kg": 'קג',
      "cm": 'סמ',
      "A little more and we're done": 'עוד קצת וסיימנו',
      "Street": "רחוב",
      "Postal code": 'מיקוד',
      "Apartment": 'דירה',
      "House": 'בית',
      "City": 'עיר',
      "Personal status": 'סטטוס אישי',
      "Occupation": 'עיסוק',
      "Are there any medical problems/diseases you suffer from":
          'האם קיימות בעיות רפואיות/ מחלות מהן את סובלת?',
      "No": 'לא',
      "Yes": 'כן',
      "Have you ever been hospitalized in the past? (excluding childbirth)":
          "האם היית מאושפזת בעבר בבית חולים? (למעט לידות)",
      "Description": "תיאור",
      "Next question": "שאלה הבאה",
      "We finished!": "סיימנו!",
      "Previous question": "שאלה קודמת",
      "Female": 'נקבה',
      'Male': 'זכר',
      'Regular Period': 'מחזור רגיל',
      'Irregular Period': 'מחזור לא סדיר',
      'Breastfeeding Period': 'מחזור הנקה',
      'Pregnant Period': 'מחזור בהריון',
      'Not accepting anymore': 'לא מקבלת יותר',
      'is required': 'נדרש',
      'So what is actually a quarter to seven': 'אז מה זה בעצם רבע לשובע?',
      "Let's get started": "בואו נתחיל",
      "Camera": 'מצלמה',
      'Gallery': 'גלריה',
      'Store': 'חנות',
      'My stars': 'הכוכבים שלי',
      'Hizukit Mehadas': 'חיזוקית מהדס',
      'Products & recipes': 'מוצרים ומתכונים',
      'My plan': 'התוכנית שלי',
      'Home page': 'דף הבית',
      'Personal area': 'איזור אישי',
      'Nutrition plans': 'תוכניות תזונה',
      'Ice Therapy': 'רפואת קרח',
      'Articles': 'מאמרים',
      'Podcasts': 'פודקאסטים',
      'Workshops and events': 'הסדנאות והאירועים',
      'Healthy consumption': 'צרכנות בריאה',
      'Contact': 'צור קשר',
      'Terms and Conditions': 'תקנון ותנאי שימוש',
      'General messages': 'הודעות כלליות',
      'My orders': 'ההזמנות שלי',
      'The products I loved': 'המוצרים שאהבתי',
      'My workshops/events': 'סדנאות/ אירועים שלי',
      'My shopping cart': 'סל הקניות שלי',
      'The recipes I loved': 'המתכונים שאהבתי',
      'Tools': 'כלים',
      'Weight and measurements tracking': 'מעקב שקילה והיקפים',
      'My plans': 'התוכניות שלי',
      'Personal profile': 'פרופיל אישי',
      'General': 'כללי',
      'Image editing': 'עריכת תמונה',
      "My shopping list": 'רשימת הקניות שלי',
      "My Favorite Recipes": 'המתכונים שאהבתי',
      "Accessibility": "נגישות",
      "Terms of use policy": "תקנון תנאי שימוש",
      "Privacy policy": "תקנון פרטיות",
      "Shipping and returns policy": 'תקנון משלוחים והחזרות',
      "Regulations": "תקנונים",
      "General information and contact details": "מידע כללי ונתוני התקשרות",
      "Body data and medical information": "נתוני גוף ומידע רפואי",
      "Back to": "חזרה",
      "Edit": "עריכה",
      "Login details": "פרטי התחברות",
      "Save changes": "שמירת שינויים",
      "New password": "סיסמה חדשה",
      "Your request to change the password has been received. Please confirm the change in the email updated in the system within 48 hours":
          "בקשתך לשינוי סיסמא התקבלה יש לאשר את השינוי במייל שמעודכן במערכת תוך 48 שעות.",
      "Date of Birth": "תאריך לידה",
      "Body data": "נתוני גוף",
      "Medical questionnaire": "שאלון רפואי",
      "Viewing blood test form": "צפייה בטופס בדיקות דם",
      "Enter ovulation_calculator calculator": "כניסה למחשבון ביוץ",
      "Contact Us": "יצירת קשר",
      "Coach Chat": "צ’אט מאמנת",
      "Technical Support": "עזרה טכנית",
      "Inquiry Regarding Service": "פנייה בעניין שירות",
      "Send": "שליחה",
      "I need help with": "אני זקוק/ה לעזרה ב",
      "Details": "פירוט",
      "Thank you for your inquiry!": "תודה על פנייתך!",
      "Your inquiry will be handled within 24 hours": "פנייתך תטופל תוך 24 שעות",
      "Return to homepage": "חזרה לעמוד הבית",
      "Married": "נשוי/נשואה",
      "Unmarried": "רווק/רווקה",
      "Jerusalem": "ירושלים",
      "Tel Aviv-Yafo": "תל אביב-יפו",
      "Haifa": "חיפה",
      "Rishon LeZion": "ראשון לציון",
      "Ashdod": "אשדוד",
      "Beersheba": "באר שבע",
      "Petah Tikva": "פתח תקווה",
      "Netanya": "נתניה",
      "Holon": "חולון",
      "Bnei Brak": "בני ברק",
      "Bat Yam": "בת ים",
      "Ramat Gan": "רמת גן",
      "Ashkelon": "אשקלון",
      "Rehovot": "רחובות",
      "Beit Shemesh": "בית שמש",
      "Kfar Saba": "כפר סבא",
      "Herzliya": "הרצליה",
      "Hadera": "חדרה",
      "Modi'in-Maccabim-Re'ut": "מודיעין-מכבים-רעות",
      "Eilat": "אילת",
      "Logout": "התנתקות",
      "Are you sure you want to log out": "האם אתה בטוח שאתה רוצה להתנתק?",
      "OTP is being sent to your email. Please check your email and fill it in":
          'קוד האימות נשלח לדוא"ל שלך. אנא בדוק את הדוא"ל שלך ומלא אותו.',
      "Good morning": "בוקר טוב",
      "Good afternoon": "צהריים טובים",
      "Good evening": "ערב טוב",
      "What's on the agenda for today?": "אז מה היום בתוכנית?",
      "Delete": "מחיקה",
      "Select All": "בחר הכל",
      "Ovulation Calculator": "מחשבון ביוץ",
      "Daily Nutrition Planning": "תכנון תזונה יומי",
      "Daily Reports": "דוחות יומיים",
      "Daily Report": "דוח יומי",
      "Daily Report - Day {}": "הדוח היומי- יום {}",
      "Weekly Reports": "דוחות שבועיים",
      "Weekly Report": "דוח שבועי",
      "Weekly Report - No. {}": "הדוח השבועי - מס’ {}",
      "Intuitive Writing for Myself": "כתיבה אינטואיטיבית לעצמי",
      "My Successes": "ההצלחות שלי",
      "Fasting Calculator": "מחשבון צום",
      "Nutritional Information": "מידע תזונתי",
      "Mark as Unread": "סמן כלא נקרא",
      "Mark as Read": "סמן כנקרא",
      "You have not entered the current weight yet!": "טרם הזנת משקל נוכחי!",
      "Click here to weigh yourself": "לחצי כאן כדי להישקל",
      "We will meet on {} for the next weigh-in": "ניפגש ב- {} בשקילה הבאה",
      "Previous Weigh-in Date: {}": "{} :תאריך שקילה קודם",
      "Last": "אחרון",
      "The system detects that you are ovulating, so it is not recommended to weigh yourself these days":
          "המערכת קולטת שאת בימי ביוץ ולכן לא מומלץ להישקל בימים אלו",
      "The next weigh-in will take place on": "השקילה הבאה תתקיים ב",
      "Please wait until the end of hormonal days!": "נא להמתין לסיום ימים הורמונליים!",
      "It's time to measure your circumference": "הגיע הזמן למדידת היקפים",
      "It's time for your weekly weigh-in!": "הגיע הזמן לשקילה השבועית שלך!",
      "Last Hip Line": "קו ירכיים אחרון",
      "Last Abdominal Line": "קו בטן אחרון",
      "Last Chest Line": "קו חזה אחרון",
      "Champion!": "אלופה!",
      "Very nice progress": "התקדמות יפה מאוד",
      "Keep it up": "המשיכי כך",
      "Weight Entry": "הזנת משקל",
      "Confirmation": "אישור",
      "Edit weight": "עריכת משקל",
      "View Data History": "צפייה בהיסטורית נתונים",
      "You are on the right track!": "את על הדרך הנכונה!",
      "We will meet on {} for the next measurement": "ניפגש ב- {} במדידה הבאה",
      "Weighing and Circumference Data History": "היסטוריית נתוני שקילה והיקפים",
      "Abdominal Line": "קו בטן",
      "Chest Line": "קו חזה",
      "Hip Line": "קו ירכיים",
      "First Weigh-in": "שקילה ראשונה",
      "Last Weigh-in": "שקילה אחרונה",
      "So far you have lost {} kg, which is x percent of your body weight":
          "עד כה ירדת {} ק״ג, שהם x אחוז ממשקל גופך",
      "Date": "תאריך",
      "First Measurement": "מדידה ראשונה",
      "Last Measurement": "מדידה אחרונה",
      "January": "ינואר",
      "February": "פברואר",
      "March": "מרץ",
      "April": "אפריל",
      "May": "מאי",
      "June": "יוני",
      "July": "יולי",
      "August": "אוגוסט",
      "September": "ספטמבר",
      "October": "אוקטובר",
      "November": "נובמבר",
      "December": "דצמבר",
      "Hormonal Days": "ימים הורמונליים",
      "Ovulation": "ביוץ",
      "Menstruation": "וסת",
      "Edit Data": "עריכת נתונים",
      "Menstruation Status:": "סטטוס וסת:",
      "Regular": "סדירה",
      "Save Data": "שמירת נתונים",
      "Submit": "שלח",
      "Intuitive Writing": "כתיבה אינטואיטיבית",
      "New Note": "פתק חדש",
      "Save": "שמירה",
      "list": "לרשימה",
      "To Read": "לקריאה",
      "No Data found": "לא נמצאו נתונים",
      "Breakfast": "ארוחת בוקר",
      "Mark if Done": "סמני אם ביצעת",
      "Vegetables": "ירקות",
      "Proteins": "חלבונים",
      "Carbohydrates": "פחמימות",
      "Fats": "שומנים",
      "Lunch": "ארוחת צהריים",
      "Dinner": "ארוחת ערב",
      "Send Plan to Coach": "שליחת התכנון למאמנת",
      "Confirm": "אישור",
      "Cannot Select": "לא ניתן לבחור",
      "Daily Plan Sent to Coach": "התכנון היומי נשלח למאמנת",
      "Update What You Did at the End of the Day": "בסוף היום עדכני מה ביצעת",
      "The daily plan is sent to the coach. At the end of the day, update what you have done":
          "התוכנית היומית נשלחת למאמן. בסופו של יום, עדכן מה עשית",
      "Search by free text": "חיפוש לפי טקסט חופשי",
      "Day": "יום",
      "Fasting": "צום",
      "Report approval": "אישור הדוח",
      "Not at all": "בכלל לא",
      "Very": "מאוד",
      "More than": "יותר מ-",
      "Number of Target Hours": "מספר שעות היעד",
      "I started fasting earlier": "התחלתי צום מוקדם יותר",
      "Start Fasting": "התחלת צום",
      "Start Fasting Timer": "הפעלת שעון צום",
      "Hours of Fasting {}": "{} שעות צום",
      "The target is ": "היעד הוא ",
      " hours! Ready": " שעות! מוכנה",
      "To end the fast": "לסיום הצום",
      "Press to Stop": "לחצי לעצירה",
      "Edit Fasting Timer": "עריכת שעון הצום",
      "Number of Intended Fasting Hours": "מס׳ שעות הצום המיועד",
      "Start Time": "שעת התחלה",
      "Eating window": "חלון צום",
      "For fasting editing": "-",
      "hours": "שעות",
      "Duration": "משך",
      "Add New Fast": "הוספת צום חדש",
      "Minutes": "דקות",
      "Hour": "שעה",
      "Cancel": "ביטול",
      "Update": "עדכון",
      "Fast Clock Update": "עדכון שעון צום",
      "Fast Editing": "עריכת צום",
      "Update Fasting Start Time": "עדכני את שעת התחלת הצום",
      "Fasting History": "היסטוריית צומות",
      "Products and Recipes": "מוצרים ומתכונים",
      "Recommended Products": "מוצרים מומלצים",
      "Recipes": "מתכונים",
      "Recommended": "מומלץ",
      "Add": "הוספה",
      "To Shopping List": "לרשימת הקניות",
      "Share": "שיתוף",
      "All Products": "כל המוצרים",
      "All Recipes": "כל המתכונים",
      "Filter by": "סינון לפי",
      "Sort by": "מיין לפי",
      "Vegan": "טבעוני",
      "Vegetarian": "צמחוני",
      "Meat": "בשרי",
      "Dairy": "חלבי",
      "To add to the shopping list, click on the square": "כדי להוסיף לרשימת הקניות לחצו על הריבוע",
      "Ingredients": "מרכיבים",
      "Add to shopping list": "הוספה לרשימת הקניות",
      "Most relevant": "הכי רלוונטי",
      "Most popular": "הכי פופולרי",
      "Price: Low to High": "מחיר: נמוך לגבוה",
      "Price: High to Low": "מחיר: גבוה לנמוך",
      "Add to Cart": "הוספה לסל",
      "Are you sure you want to remove item from cart": "האם אתה בטוח שברצונך להסיר את הפריט מהעגלה",
      "Checkout": "לקופה",
      "Total to be paid": "סהכ לתשלום",
      "Sub Total": "תת סך הכל",
      "You may also be interested": "יכול לעניין אותך גם",
      "Hadas's Strengthening": "חיזוקית של הדס",
      "Weekly Torah Portion": "פרשת השבוע",
      "Strength Training": "אימוני כוח",
      "Flexibility": "גמישות",
      "Learning to Cook": "לומדות לבשל",
      "To Watch": "לצפייה",
      "Order details": "פרטי הזמנה",
      "Total Amount": "סכום כולל",
      "Items": "פריטים",
      "Cancel Order": "בטל הזמנה",
      "Are you sure you want to cancel this order?": "האם אתה בטוח שברצונך לבטל הזמנה זו?",
      "Pending": "ממתין",
      "Processing": "מעובד",
      "Shipped": "נשלח",
      "Delivered": "נמסר",
      "Canceled": "בוטל",
      "Returned": "הוחזר",
      "Refunded": "הוחזר כספי",
      "Learn more": "למידע נוסף",
      "For More Details": "לפרטים נוספים",
      "On Date": "בתאריך",
      "Free of Charge": "ללא עלות",
      "NIS": "שח",
      "Participants": "משתתפים",
      "So, what's in the event?": "אז מה באירוע?",
      "Registration for {}": "הרשמה ל {}",
      "Registration": "הרשמה",
      "On the date": "בתאריך",
      "From": "משעה",
      "Past events": "אירועי עבר",
      "Are you sure you want to delete this all product?": "האם אתה בטוח שברצונך למחוק את כל המוצר הזה?",
      "Your order is on its way!": "ההזמנה בדרך אלייך!",
      "Thank you for your purchase": "תודה על רכישתך",
      "Invoice is waiting for you": "חשבונית ממתינה לך",
      "in the email: {}": "במייל: {}",
      "The delivery will arrive at your home in about 5 business days":
          "המשלוח יגיע לביתך בעוד כ- 5 ימי עסקים",
      "For questions and more details, you can contact us at: {}":
          "לשאלות ולפרטים נוספים ניתן לפנות בטל’ {}",
      "Back to Home Page": "חזרה לעמוד הבית",
      "Cycle Length (number of days between periods, usually between 26-50 days)":
          "אורך המחזור (כמה ימים בין ווסת לווסת בדר\"כ בין 26-50 ימים)",
      "Weight not entered yet": "טרם הזנת משקל נוכחי!",
      "Click here to weigh in": "לחצי כאן כדי להישקל",
      "Select all": "בחר הכל",
      "My Programs": "התוכניות שלי",
      "Continuation Programs": "תוכניות המשך",
      "Completed Programs": "תוכניות שסיימת",
      "Program Summary": "לסיכום התוכנית",
      "So what's on the agenda?": "אז מה היום בתוכנית?",
      "Lessons": "שיעורים",
      "Tasks": "משימות",
      "My principles puzzle": "פאזל העקרונות שלי",
      "Content library": "ספריית תוכן",
      "Completed {1}": "הושלמו {1}",
      "A new informational video has been uploaded": "עלה סרטון מידע חדש",
      "Lesson Summary": "לסיכום שיעור",
      "Lesson": "שיעור",
      "Remaining to Watch: {} min": "נותר לצפייה: {} דק׳",
      "To watch the video, you must complete viewing the previous video":
          "כדי לצפות בסרטון, עליך להשלים צפייה של הסרטון הקודם.",
      "At the end of the lesson, you will be able to view the lesson summary and tasks":
          "בסיום השיעור תוכלי לצפות בסיכום שיעור ובמשימות",
      "Download File": "הורדת קובץ",
      "My Tasks from the Lesson": "המשימות שלי מהשיעור",
      "All Tasks": "כל המשימות",
      "My Tasks": "המשימות שלי",
      "To the principles puzzle": "לפאזל העקרונות",
      "Show all incomplete tasks": "הצג את כל המשימות שלא בוצעו",
      "Show all": "הצג הכל",
      "In summary": "לסיכום",
      "Instructor: {}": "מנחה: {}",
      "The hour is full, {} on the waiting list": "השעה מלאה, {} ברשימת המתנה",
      "Exit from Waiting List": "יציאה מרשימת המתנה",
      "To Waiting List": "לרשימת המתנה",
      "Cancel Registration": "ביטול הרשמה",
      "Register": "להרשמה",
      "{} participants": "{} משתתפים",
      "Well done! You have completed the program and now it's time to summarize. The summary is for you and for us":
          "כל הכבוד! סיימת את התוכנית ועכשיו נשאר לסכם הסיכום הוא בשבילך ובשבילנו",
      "Click here to fill out": "לחצי כאן למילוי",
      "Program Completion Report": "דוח סיום תוכנית",
      "Finish": "סיום",
      "How do we proceed now": "איך מתקדמים עכשיו",
      "Move your heart on the scale according to your feelings": "הזיזי את הלב על הסקלה בהתאם לתחושתך",
      "Before and After Photos": "תמונות של אחרי",
      "Amazing! See your progress": "מדהימה! ראי את התקדמות שלך",
      "Thank you for participating in the program": "תודה על השתתפותך בתוכנית",
      "We look forward to seeing you in the upcoming programs": "נשמח לראותך בתוכניות ההמשך",
      "The Stars Program": "תוכנית הכוכבות",
      "Undecided? Fill out this form for advice": "מתלבטת? מלאי טופס זה לייעוץ",
      "I need advice regarding the program": "אני זקוק/ה לייעוץ בנוגע לתוכנית",
      "Please select plan": "אנא בחר תוכנית",
      "Weight and Measurement History": "היסטוריית שקילה והיקפים",
      "Weight and Measurement Data History": "היסטוריית נתוני שקילה והיקפים",
      "Summary of My Personal Journey": "סיכום התהליך האישי שלי",
      "My Victory Picture": "תמונת הניצחון שלי",
      "Before and After Pictures": "תמונות לפני ואחרי",
      "Share Photo": "שיתוף תמונה",
      "Next page": "לעמוד הבא",
      "Previous page": "לעמוד הקודם",
      "The Vegetable Challenge": "אתגר הירקות",
      "Day Number": "יום מספר",
      "Vegetable Summary until Day No. {}": "סיכום הירקות עד יום מס׳ {}",
      "Red/Orange/Purple Vegetables": "ירקות אדומים/ כתומים/ סגולים",
      "Yellow/White Vegetables": "ירקות צהובים/ לבנים",
      "Green Vegetables": "ירקות ירוקים",
      "Total Vegetables": "סה״כ ירקות",
      "Which vegetables do you plan to have today?": "איזה ירקות את מתכננת להיום?",
      "At 20:00 you can confirm the final daily list and add to the challenge summary":
          "בשעה 20:00 תוכלי לאשר את הרשימה היומית הסופית ולהוסיף לסיכום האתגר",
      "Already Selected Before": "כבר נבחר בעבר",
      "Great! Add to the Weekly Summary": "אשרי והוסיפי לסיכום השבועי",
      "So far you have earned {} stars!": "עד כה צברת {} כוכבים!",
      "Good morning, {}": "בוקר טוב, {}",
      "Good afternoon, {}": "צהריים טובים, {}",
      "Good evening, {}": "ערב טוב, {}",
      "Good night, {}": "לילה טוב, {}",
      "Hello, {}": "שלום, {}",
      "So what's on the agenda today?": "אז מה היום בתוכנית?",
      "Ovulation forecast": "צפי ביוץ",
      "Expected period": "וסת צפויה",
      "For period editing": "לעריכת וסת",
      "For fast editing": "לעריכת צום",
      "days": "יום",
      "Cycle day": "יום המחזור",
      "Weighing": "שקילה",
      "Click here and weigh me": "לחצי כאן והישקלי",
      "Nutrition": "תזונה",
      "Weekly portion": "פרשת השבוע",
      "For me": "בשבילי",
      "The daily report must be filled out": "יש למלא את הדוח היומי",
      "The weekly report must be filled out": "יש למלא את הדוח השבועי",
      "completed the program home":
          "כל הכבוד! סיימת את התוכנית ועכשיו נשאר לסכם הסיכום הוא בשבילך ובשבילנו",
      "Click here to fill it out": "לחצו כאן למילוי",
      "Ice workshop": "סדנת קרח",
      "Welcome to {1}, our next meeting will be at {2}, see you there!":
          "ברוכים הבאים אל {1}, הפגישה הבאה שלנו תהיה ב-{2}, נתראה שם!",
      "Please complete all the answers": "נא להשלים את כל התשובות",
      "Reminder to Fill Reports": "תזכורת למילוי דוחות",
      "Daily planning needs to be filled out": "יש למלא תכנון יומי",
      "A report is available for completion": "קיים דוח למילוי",
      "Hey Sorry! Classes are closed today": "היי סליחה! השיעורים סגורים היום",
      "Join the class on the link": "כנסי לשיעור בלינק",
      "Ovulation expected": "צפי ביוץ",
      "Menstruation expected": "וסת צפויה",
      "customer": "לָקוּחַ",
      "Customer Options": "אפשרויות לקוח",
      "Chat": "לְשׂוֹחֵחַ",
      "blood report information": "מידע על דוחות דם",
      "Nutrition planning": "תכנון תזונה",
      "snacks": "נשנושים",
      "Shopping list is empty":"רשימת הקניות ריקה",
      "Vegetable challenge will start after {} days":"אתגר הירקות יתחיל לאחר {} ימים",
      "No coach found":"לא נמצא מאמן",
    },
  };

  @override
  Map<String, Map<String, String>> get keys => translations;

  static String getKeyForValue(String value, String locale) {
    return translations[locale]
            ?.entries
            .firstWhere((entry) => entry.value == value, orElse: () => MapEntry('', value))
            .key ??
        value;
  }

  static String translateValue(String value, String targetLocale) {
    String key = getKeyForValue(value, 'he_IL'); //
    return translations[targetLocale]?[key] ?? value;
  }
}

extension LocalizationHelper on String {
  String translateValue(String locale) {
    return Localization.translateValue(this, locale);
  }
}
